name: Deploy Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 159.223.169.222
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/ypet/staging/frontend
            git pull origin main
            pnpm install --frozen-lockfile
            pnpm build
            pm2 restart ypet-staging-front
